[2024-11-03T10:09:31.175+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-03T10:09:31.188+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_hooks.plot_github scheduled__2024-10-30T13:30:00+00:00 [queued]>
[2024-11-03T10:09:31.192+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_hooks.plot_github scheduled__2024-10-30T13:30:00+00:00 [queued]>
[2024-11-03T10:09:31.192+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-03T10:09:31.197+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): plot_github> on 2024-10-30 13:30:00+00:00
[2024-11-03T10:09:31.202+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=237) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-03T10:09:31.204+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks', 'plot_github', 'scheduled__2024-10-30T13:30:00+00:00', '--job-id', '1265', '--raw', '--subdir', 'DAGS_FOLDER/Stock_pred.py', '--cfg-path', '/tmp/tmp_09olu0r']
[2024-11-03T10:09:31.204+0000] {standard_task_runner.py:64} INFO - Started process 292 to run task
[2024-11-03T10:09:31.205+0000] {standard_task_runner.py:91} INFO - Job 1265: Subtask plot_github
[2024-11-03T10:09:31.226+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_postgres_hooks.plot_github scheduled__2024-10-30T13:30:00+00:00 [running]> on host b7aba691e1ff
[2024-11-03T10:09:31.263+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_postgres_hooks' AIRFLOW_CTX_TASK_ID='plot_github' AIRFLOW_CTX_EXECUTION_DATE='2024-10-30T13:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-30T13:30:00+00:00'
[2024-11-03T10:09:31.264+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-03T10:09:39.094+0000] {logging_mixin.py:188} INFO - images/thumbs/01.jpg UPDATED
[2024-11-03T10:09:46.181+0000] {logging_mixin.py:188} INFO - images/fulls/01.jpg UPDATED
[2024-11-03T10:09:46.187+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-03T10:09:46.187+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-03T10:09:46.202+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_hooks, task_id=plot_github, run_id=scheduled__2024-10-30T13:30:00+00:00, execution_date=20241030T133000, start_date=20241103T100931, end_date=20241103T100946
[2024-11-03T10:09:46.232+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-11-03T10:09:46.248+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-03T10:09:46.249+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
