[2024-07-03T15:52:46.286+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T15:52:46.295+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.create_postgres_table manual__2024-07-03T15:52:45.147399+00:00 [queued]>
[2024-07-03T15:52:46.298+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.create_postgres_table manual__2024-07-03T15:52:45.147399+00:00 [queued]>
[2024-07-03T15:52:46.298+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-03T15:52:46.303+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2024-07-03 15:52:45.147399+00:00
[2024-07-03T15:52:46.306+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=197) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-03T15:52:46.307+0000] {standard_task_runner.py:63} INFO - Started process 199 to run task
[2024-07-03T15:52:46.307+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'create_postgres_table', 'manual__2024-07-03T15:52:45.147399+00:00', '--job-id', '270', '--raw', '--subdir', 'DAGS_FOLDER/sql.py', '--cfg-path', '/tmp/tmpl93za9s6']
[2024-07-03T15:52:46.308+0000] {standard_task_runner.py:91} INFO - Job 270: Subtask create_postgres_table
[2024-07-03T15:52:46.325+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.create_postgres_table manual__2024-07-03T15:52:45.147399+00:00 [running]> on host 73a0e5a00b20
[2024-07-03T15:52:46.354+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v03' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2024-07-03T15:52:45.147399+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-03T15:52:45.147399+00:00'
[2024-07-03T15:52:46.355+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T15:52:46.355+0000] {sql.py:276} INFO - Executing: 
            create table if not exists dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        
[2024-07-03T15:52:46.358+0000] {base.py:84} INFO - Using connection ID 'Postgres' for task execution.
[2024-07-03T15:52:46.362+0000] {base.py:84} INFO - Using connection ID 'Postgres' for task execution.
[2024-07-03T15:52:46.363+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T15:52:46.363+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 431, in run
    with self._create_autocommit_connection(autocommit) as conn:
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 551, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 175, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "jdbc:postgresql://localhost:5433/postgres" to address: Name or service not known

[2024-07-03T15:52:46.367+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_with_postgres_operator_v03, task_id=create_postgres_table, run_id=manual__2024-07-03T15:52:45.147399+00:00, execution_date=20240703T155245, start_date=20240703T155246, end_date=20240703T155246
[2024-07-03T15:52:46.371+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 270 for task create_postgres_table (could not translate host name "jdbc:postgresql://localhost:5433/postgres" to address: Name or service not known
; 199)
[2024-07-03T15:52:46.410+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-03T15:52:46.414+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-07-03T15:52:46.431+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T15:52:46.434+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
