[2024-08-05T09:35:39.584+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-05T09:35:39.593+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_hooks.pred_time_series manual__2024-08-05T09:35:22.922232+00:00 [queued]>
[2024-08-05T09:35:39.596+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_hooks.pred_time_series manual__2024-08-05T09:35:22.922232+00:00 [queued]>
[2024-08-05T09:35:39.596+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-05T09:35:39.601+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): pred_time_series> on 2024-08-05 09:35:22.922232+00:00
[2024-08-05T09:35:39.606+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=379) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-05T09:35:39.606+0000] {standard_task_runner.py:64} INFO - Started process 390 to run task
[2024-08-05T09:35:39.607+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks', 'pred_time_series', 'manual__2024-08-05T09:35:22.922232+00:00', '--job-id', '734', '--raw', '--subdir', 'DAGS_FOLDER/Stock_pred.py', '--cfg-path', '/tmp/tmp8krek57d']
[2024-08-05T09:35:39.607+0000] {standard_task_runner.py:91} INFO - Job 734: Subtask pred_time_series
[2024-08-05T09:35:39.623+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_postgres_hooks.pred_time_series manual__2024-08-05T09:35:22.922232+00:00 [running]> on host de0da25eb647
[2024-08-05T09:35:39.652+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_postgres_hooks' AIRFLOW_CTX_TASK_ID='pred_time_series' AIRFLOW_CTX_EXECUTION_DATE='2024-08-05T09:35:22.922232+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-05T09:35:22.922232+00:00'
[2024-08-05T09:35:39.652+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-05T09:35:39.727+0000] {warnings.py:112} WARNING - /opt/***/dags/Stock_pred.py:266: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new_ts.rename(index={0:date},inplace=True)

[2024-08-05T09:35:39.734+0000] {base.py:84} INFO - Using connection ID 'postgres_server_2' for task execution.
[2024-08-05T09:35:39.818+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/keras/src/saving/saving_lib.py:576: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 7 variables whereas the saved optimizer has 12 variables. 
  saveable.load_own_variables(weights_store.get(inner_path))

[2024-08-05T09:35:39.911+0000] {logging_mixin.py:188} INFO - 1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step
[2024-08-05T09:35:39.912+0000] {logging_mixin.py:188} INFO - 1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step
[2024-08-05T09:35:39.918+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-05T09:35:39.918+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-05T09:35:39.921+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_hooks, task_id=pred_time_series, run_id=manual__2024-08-05T09:35:22.922232+00:00, execution_date=20240805T093522, start_date=20240805T093539, end_date=20240805T093539
[2024-08-05T09:35:39.952+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-05T09:35:39.962+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-05T09:35:39.963+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
