[2024-08-30T08:26:36.048+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-30T08:26:36.056+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_hooks.monitoring scheduled__2024-08-28T13:30:00+00:00 [queued]>
[2024-08-30T08:26:36.059+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_hooks.monitoring scheduled__2024-08-28T13:30:00+00:00 [queued]>
[2024-08-30T08:26:36.059+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-30T08:26:36.064+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): monitoring> on 2024-08-28 13:30:00+00:00
[2024-08-30T08:26:36.070+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=85) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-30T08:26:36.070+0000] {standard_task_runner.py:64} INFO - Started process 108 to run task
[2024-08-30T08:26:36.071+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks', 'monitoring', 'scheduled__2024-08-28T13:30:00+00:00', '--job-id', '972', '--raw', '--subdir', 'DAGS_FOLDER/Stock_pred.py', '--cfg-path', '/tmp/tmptbtr0xow']
[2024-08-30T08:26:36.072+0000] {standard_task_runner.py:91} INFO - Job 972: Subtask monitoring
[2024-08-30T08:26:36.089+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_postgres_hooks.monitoring scheduled__2024-08-28T13:30:00+00:00 [running]> on host b7aba691e1ff
[2024-08-30T08:26:36.125+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_postgres_hooks' AIRFLOW_CTX_TASK_ID='monitoring' AIRFLOW_CTX_EXECUTION_DATE='2024-08-28T13:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-28T13:30:00+00:00'
[2024-08-30T08:26:36.126+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-30T08:26:36.130+0000] {base.py:84} INFO - Using connection ID 'postgres_server_2' for task execution.
[2024-08-30T08:26:36.160+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-30T08:26:36.160+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Stock_pred.py", line 424, in monitoring
    df_old_clf['Target'].iloc[-1] = input_clf['Target']
                                    ~~~~~~~~~^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2024-08-30T08:26:36.164+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_with_postgres_hooks, task_id=monitoring, run_id=scheduled__2024-08-28T13:30:00+00:00, execution_date=20240828T133000, start_date=20240830T082636, end_date=20240830T082636
[2024-08-30T08:26:36.171+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 972 for task monitoring ('NoneType' object is not subscriptable; 108)
[2024-08-30T08:26:36.209+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-30T08:26:36.213+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
