[2025-04-11T12:35:56.210+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-11T12:35:56.218+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Stock_prediction_udpate.get_src_tables manual__2025-04-11T12:35:51.308411+00:00 [queued]>
[2025-04-11T12:35:56.222+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Stock_prediction_udpate.get_src_tables manual__2025-04-11T12:35:51.308411+00:00 [queued]>
[2025-04-11T12:35:56.222+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-11T12:35:56.227+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): get_src_tables> on 2025-04-11 12:35:51.308411+00:00
[2025-04-11T12:35:56.240+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=779) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-11T12:35:56.241+0000] {standard_task_runner.py:72} INFO - Started process 783 to run task
[2025-04-11T12:35:56.242+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Stock_prediction_udpate', 'get_src_tables', 'manual__2025-04-11T12:35:51.308411+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/Update.py', '--cfg-path', '/tmp/tmpdocjp26l']
[2025-04-11T12:35:56.244+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask get_src_tables
[2025-04-11T12:35:56.273+0000] {task_command.py:467} INFO - Running <TaskInstance: Stock_prediction_udpate.get_src_tables manual__2025-04-11T12:35:51.308411+00:00 [running]> on host c485992206db
[2025-04-11T12:35:56.311+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Stock_prediction_udpate' AIRFLOW_CTX_TASK_ID='get_src_tables' AIRFLOW_CTX_EXECUTION_DATE='2025-04-11T12:35:51.308411+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-11T12:35:51.308411+00:00'
[2025-04-11T12:35:56.312+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-11T12:35:56.329+0000] {base.py:84} INFO - Retrieving connection 'postgres'
[2025-04-11T12:35:56.357+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/common/sql/hooks/sql.py:287: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return psql.read_sql(sql, con=conn, params=parameters, **kwargs)

[2025-04-11T12:35:56.678+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-11T12:35:56.702+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-11T12:35:56.702+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=Stock_prediction_udpate, task_id=get_src_tables, run_id=manual__2025-04-11T12:35:51.308411+00:00, execution_date=20250411T123551, start_date=20250411T123556, end_date=20250411T123556
[2025-04-11T12:35:56.755+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-11T12:35:56.766+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-11T12:35:56.767+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
