[2024-07-18T08:11:06.910+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-18T08:11:06.918+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_hooks.concat_data manual__2024-07-18T08:11:03.799517+00:00 [queued]>
[2024-07-18T08:11:06.921+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_hooks.concat_data manual__2024-07-18T08:11:03.799517+00:00 [queued]>
[2024-07-18T08:11:06.921+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-18T08:11:06.925+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): concat_data> on 2024-07-18 08:11:03.799517+00:00
[2024-07-18T08:11:06.928+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1426) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-18T08:11:06.929+0000] {standard_task_runner.py:63} INFO - Started process 1435 to run task
[2024-07-18T08:11:06.929+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks', 'concat_data', 'manual__2024-07-18T08:11:03.799517+00:00', '--job-id', '139', '--raw', '--subdir', 'DAGS_FOLDER/sql_2.py', '--cfg-path', '/tmp/tmpyt8nck8e']
[2024-07-18T08:11:06.930+0000] {standard_task_runner.py:91} INFO - Job 139: Subtask concat_data
[2024-07-18T08:11:06.945+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_postgres_hooks.concat_data manual__2024-07-18T08:11:03.799517+00:00 [running]> on host 0c2114842aea
[2024-07-18T08:11:06.976+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_postgres_hooks' AIRFLOW_CTX_TASK_ID='concat_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-18T08:11:03.799517+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-18T08:11:03.799517+00:00'
[2024-07-18T08:11:06.977+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-18T08:11:06.979+0000] {base.py:84} INFO - Using connection ID 'postgres_server_2' for task execution.
[2024-07-18T08:11:07.033+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-18T08:11:07.033+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-18T08:11:07.037+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_hooks, task_id=concat_data, run_id=manual__2024-07-18T08:11:03.799517+00:00, execution_date=20240718T081103, start_date=20240718T081106, end_date=20240718T081107
[2024-07-18T08:11:07.068+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-18T08:11:07.079+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-18T08:11:07.079+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
