[2024-12-10T20:17:16.024+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-10T20:17:16.035+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_hooks.get_src_tables scheduled__2024-12-09T13:30:00+00:00 [queued]>
[2024-12-10T20:17:16.038+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_hooks.get_src_tables scheduled__2024-12-09T13:30:00+00:00 [queued]>
[2024-12-10T20:17:16.038+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-10T20:17:16.043+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_src_tables> on 2024-12-09 13:30:00+00:00
[2024-12-10T20:17:16.050+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=85) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-10T20:17:16.051+0000] {standard_task_runner.py:64} INFO - Started process 96 to run task
[2024-12-10T20:17:16.052+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks', 'get_src_tables', 'scheduled__2024-12-09T13:30:00+00:00', '--job-id', '1358', '--raw', '--subdir', 'DAGS_FOLDER/Stock_pred.py', '--cfg-path', '/tmp/tmpgrsgg9dc']
[2024-12-10T20:17:16.052+0000] {standard_task_runner.py:91} INFO - Job 1358: Subtask get_src_tables
[2024-12-10T20:17:16.072+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_postgres_hooks.get_src_tables scheduled__2024-12-09T13:30:00+00:00 [running]> on host b7aba691e1ff
[2024-12-10T20:17:16.113+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_postgres_hooks' AIRFLOW_CTX_TASK_ID='get_src_tables' AIRFLOW_CTX_EXECUTION_DATE='2024-12-09T13:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-09T13:30:00+00:00'
[2024-12-10T20:17:16.114+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-10T20:17:16.118+0000] {base.py:84} INFO - Using connection ID 'postgres_server_2' for task execution.
[2024-12-10T20:17:16.133+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/common/sql/hooks/sql.py:269: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return psql.read_sql(sql, con=conn, params=parameters, **kwargs)

[2024-12-10T20:17:16.175+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-12-10T20:17:16.176+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-10T20:17:16.181+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_hooks, task_id=get_src_tables, run_id=scheduled__2024-12-09T13:30:00+00:00, execution_date=20241209T133000, start_date=20241210T201716, end_date=20241210T201716
[2024-12-10T20:17:16.231+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-12-10T20:17:16.245+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-10T20:17:16.245+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
